### PR TITLE
Project 3: Second Milestone for TIC TAC TOE game.

### PR DESCRIPTION
**Pull request by FdI96**
-main.rb: file with the basic flow of the game
-README.md: file with more information.
-.rubocop.yml: little change of "Metrics/BlockLength Max: 45" (changed from 30 to 45)

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've made laudable progress in this milestone. You also did well by including a decent readme to this milestone, which is not a required feature :clap:  
However, some changes are required before it can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**
_**Please note that no game logic (for example checking who is a winner) is required in this milestone - instead, you can just display "The winner is X" no matter who won. Usage of inline comments in this milestone is allowed.**_
- [x] Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. You can always disable a particular cop (rule) for either a line or block of code. [This thread](https://stackoverflow.com/questions/40221797/rails-rubocop-disable-class-has-too-many-lines-error) might help.
- [x] Your game should inform the player if the selected move is a winning move (without computing the winning move)
- [x] It should also inform the player if the selected move is a draw move (without computing draw)
- [x] You don't have to loop through all the available moves before you terminate the loop. This is because there might be a draw instance while some moves are still available. Therefore, It is recommended that you call actions repeated for each move. Check the code snippet below for a better explanation:
```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end

```

**[OPTIONAL CHANGES]**

- [x] Kindly find a way to display your game board in grid form.

* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've made laudable progress in this milestone. Most of the previously required changes have been made :clap: 
However, some changes are required before you can move on. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] #p_one_turn & #p_two_turn methods looks similar. You might want to refactor your codebase to avoid unnecessary redundancy. You should be able to use a single method for the players' turn.
- [x] #win_or_draw_pone & #win_or_draw_ptwo also looks similar. Kindly find a way to make your code [DRY](https://dzone.com/articles/is-your-code-dry-or-wet) 
- [x] It does not look good to print the win and draw statements at the same time. 

**[ OPTIONAL CHANGES ]**

- [x] You might want to check your print statements at the end of the game. You're printing some unnecessary variables/strings like game on, ENTERED, etc.



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGE REQUIRED!! :recycle: 
--------------
Hello team!!! :wave: you are doing an amazing job on this milestone :muscle: 
There is a few changes to make :hammer_and_wrench: 
-------------------

- [x] The game just allows me to make  6 or 5 moves on the board, checks the counter (accu) in every turn, it looks that is counting by 2 every turn.
-------------------
Make the required changes and send it to another review. :smile: :muscle: 
HAPPY CODING!!! :grinning:

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUESTED ♻

### Hey, nice project so far. I noticed that you are missing some key features of this project, so we have to improve a few things before moving on:

- [ ] Remove those obvious explanatory comments. Only comment the strictly necessary.
- [ ] I got this error `bin/main.rb:73:in '<main>': uninitialized constant WrongOption (NameError)` please fix it;
- [ ] Your main.rb has 143 lines which is wired, looks like you have other game in it;

## As always, I wish you all the very best and see you at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED!! :recycle: 
----------------
Hey there!! :wave: You are doing an amazing job!! :muscle: :1st_place_medal: 
There are changes to make :hammer_and_wrench: 
-------------

- [x] Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. 

------------------------

Make the required changes and ask for anther review :+1: :wrench: 
HAPPPY CODDING!!
programming

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, I'd love to congratulate you on this HUGE effort you've made on this milestone.
**First**, I loved the coin feature you've implemented in the game.
**Second**, you've declared a very descent README file which isn't required on this milestone
**Third**, you've worked your way out of all your previous required changes and made 'em all. However, there are still a few changes to make before moving on

- [ ] There are still some commented code that it's not necessary to exist in your file so please remove it.
- [ ] When I select 'Tails', it raises this error ```bin/main.rb:43:in `player_turn': wrong number of arguments (given 3, expected 2) (ArgumentError)``` Please fix that

<hr>

Good luck with the next and happy coding 👨‍💻💻

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Request changes :full_moon:
**Good job so far on this milestone:clap::clap:. However, we still need to make a few changes to get this project approved :muscle:.**

**Mandatory Requirements**

- [ ] Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students.  The .rubocop.yml is currently altered. Copy and use a fresh one. use this link: https://github.com/microverseinc/linters-config/tree/master/ruby for guidance.

- [ ] Students can just display "The winner is X" no matter who won. currently, it displays the name of the winner. see screen-shot for reference: https://imgur.com/a/GlaWpeS. Please fix this.

Make the above required changes and when you are done, submit for another review.
Kindly drop your questions :point_down: if you have any and ping me on slack @ Eric Enaburekhan to respond.
Happy Coding :blush:
Eric Enaburekhan

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hey guys**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
